// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ranna.Task2.DataAccess.Context;

#nullable disable

namespace Ranna.Task2.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ranna.Task2.Entities.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Bilgi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Resim")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Urunler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Klavye",
                            Bilgi = "Yazma aracı",
                            Fiyat = 5.99m,
                            Kod = "KOD-00001",
                            OlusturmaTarihi = new DateTime(2024, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Mouse",
                            Bilgi = "Fare",
                            Fiyat = 15.49m,
                            Kod = "KOD-00002",
                            OlusturmaTarihi = new DateTime(2025, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Monitör",
                            Bilgi = "Görüntüleme cihazı",
                            Fiyat = 200.50m,
                            Kod = "KOD-00003",
                            OlusturmaTarihi = new DateTime(2025, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Bilgisayar",
                            Bilgi = "Masaüstü Bilgisayar",
                            Fiyat = 1500.00m,
                            Kod = "KOD-00004",
                            OlusturmaTarihi = new DateTime(2024, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Yazıcı",
                            Bilgi = "HP Yazıcı",
                            Fiyat = 300.00m,
                            Kod = "KOD-00005",
                            OlusturmaTarihi = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Tarayıcı",
                            Bilgi = "Toshiba Tarayıcı",
                            Fiyat = 250.00m,
                            Kod = "KOD-00006",
                            OlusturmaTarihi = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Ad = "Webcam",
                            Bilgi = "Logitech Kamera",
                            Fiyat = 50.00m,
                            Kod = "KOD-00007",
                            OlusturmaTarihi = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Ad = "Kulaklık",
                            Bilgi = "JBL Kulaklık",
                            Fiyat = 30.00m,
                            Kod = "KOD-00008",
                            OlusturmaTarihi = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Ad = "USB Bellek",
                            Bilgi = "256GB USB Bellek",
                            Fiyat = 20.00m,
                            Kod = "KOD-00009",
                            OlusturmaTarihi = new DateTime(2025, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Ad = "Harici Disk",
                            Bilgi = "2TB Harici Disk",
                            Fiyat = 100.00m,
                            Kod = "KOD-00010",
                            OlusturmaTarihi = new DateTime(2025, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
